### ISSUE TITLE
spelunker view does not match raw geojson data

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-www-spelunker#129] opened 2017-09-21 12:49 UTC
heya,

I was looking at this record today https://whosonfirst.mapzen.com/spelunker/id/890413117/ and the spelunker view shows:

```
Hierarchy
the continent of Oceania
the country of France
the dependency of New Caledonia
the region of Sud
```

but when I look at the raw geojson, it shows:

```
"wof:hierarchy": [],
```

it's super confusing when using the spelunker for debugging, I expected the web view to be the same as the data and so ended up wasting a bunch of time chasing my own tail :(

**Comment by thisisaaronland** [comment] 2017-10-02 20:37
Closing because this is basically a dupe of issue #128, as in it's an ES indexing issue.

**Closed by thisisaaronland** 2017-10-02 20:37 UTC

**Comment by thisisaaronland** [comment] 2017-10-02 23:08
So many ways to hate Elasticsearch...

```
'{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [mz:min_zoom]"}],"type":"mapper_parsing_exception","reason":"failed to parse [\
mz:min_zoom]","caused_by":{"type":"number_format_exception","reason":"For input string: \\"6.0\\""}},"status":400}'
```
